import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useGetDashboardStats } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { BedDouble, Image as ImageIcon, Inbox, Star, Settings } from 'lucide-react';
export default function Dashboard() {
    const { data: stats, isLoading } = useGetDashboardStats();
    if (isLoading) {
        return _jsxs("div", { className: "animate-pulse space-y-6", children: [_jsx("div", { className: "h-8 bg-muted rounded w-1/4" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: [1, 2, 3, 4].map(i => _jsx("div", { className: "h-32 bg-muted rounded-sm" }, i)) })] });
    }
    const statCards = [
        { label: 'Total Rooms', value: stats?.totalRooms || 0, icon: BedDouble, href: '/admin/rooms' },
        { label: 'Pending Bookings', value: stats?.pendingBookings || 0, icon: Inbox, href: '/admin/bookings' },
        { label: 'Gallery Images', value: stats?.totalGalleryImages || 0, icon: ImageIcon, href: '/admin/gallery' },
        { label: 'Media Files', value: stats?.totalMediaFiles || 0, icon: ImageIcon, href: '/admin/media' },
    ];
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-serif text-primary", children: "Dashboard" }), _jsx("p", { className: "text-muted-foreground mt-2", children: "Overview of Neel Kamal Homestay" })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: statCards.map((stat, i) => (_jsxs(Link, { href: stat.href, className: "bg-card p-6 rounded-sm border border-border shadow-sm hover:shadow-md transition-shadow group flex items-center gap-4", children: [_jsx("div", { className: "p-3 bg-primary/10 text-primary rounded-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors", children: _jsx(stat.icon, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground uppercase tracking-wider", children: stat.label }), _jsx("h3", { className: "text-3xl font-serif text-foreground mt-1", children: stat.value })] })] }, i))) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-8", children: [_jsxs("div", { className: "bg-card rounded-sm border border-border overflow-hidden", children: [_jsxs("div", { className: "p-6 border-b border-border flex justify-between items-center", children: [_jsx("h2", { className: "font-serif text-xl text-primary", children: "Recent Bookings" }), _jsx(Link, { href: "/admin/bookings", className: "text-sm text-primary hover:underline", children: "View All" })] }), _jsx("div", { className: "divide-y divide-border", children: stats?.recentBookings && stats.recentBookings.length > 0 ? (stats.recentBookings.map(booking => (_jsxs("div", { className: "p-4 flex items-center justify-between hover:bg-muted/30", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium text-foreground", children: booking.guestName }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [new Date(booking.checkIn).toLocaleDateString(), " - ", new Date(booking.checkOut).toLocaleDateString()] })] }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: `text-xs px-2 py-1 uppercase tracking-wider rounded-sm ${booking.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                                                        booking.status === 'confirmed' ? 'bg-green-100 text-green-800' :
                                                            'bg-red-100 text-red-800'}`, children: booking.status }), _jsx("p", { className: "text-sm text-muted-foreground mt-1", children: booking.roomName || 'Any Room' })] })] }, booking.id)))) : (_jsx("div", { className: "p-8 text-center text-muted-foreground", children: "No recent bookings" })) })] }), _jsxs("div", { className: "bg-card rounded-sm border border-border overflow-hidden", children: [_jsx("div", { className: "p-6 border-b border-border", children: _jsx("h2", { className: "font-serif text-xl text-primary", children: "Quick Actions" }) }), _jsxs("div", { className: "p-6 grid grid-cols-2 gap-4", children: [_jsxs(Link, { href: "/admin/rooms", className: "flex flex-col items-center justify-center p-6 border border-border rounded-sm hover:bg-muted transition-colors gap-3", children: [_jsx(BedDouble, { className: "w-8 h-8 text-primary" }), _jsx("span", { className: "text-sm font-medium", children: "Manage Rooms" })] }), _jsxs(Link, { href: "/admin/settings", className: "flex flex-col items-center justify-center p-6 border border-border rounded-sm hover:bg-muted transition-colors gap-3", children: [_jsx(Settings, { className: "w-8 h-8 text-primary" }), _jsx("span", { className: "text-sm font-medium", children: "Update Settings" })] }), _jsxs(Link, { href: "/admin/gallery", className: "flex flex-col items-center justify-center p-6 border border-border rounded-sm hover:bg-muted transition-colors gap-3", children: [_jsx(ImageIcon, { className: "w-8 h-8 text-primary" }), _jsx("span", { className: "text-sm font-medium", children: "Manage Gallery" })] }), _jsxs(Link, { href: "/admin/reviews", className: "flex flex-col items-center justify-center p-6 border border-border rounded-sm hover:bg-muted transition-colors gap-3", children: [_jsx(Star, { className: "w-8 h-8 text-primary" }), _jsx("span", { className: "text-sm font-medium", children: "Manage Reviews" })] })] })] })] })] }));
}
